#!/usr/bin/env python3
"""
MVP Model Downloader - Ready-to-Use Pre-trained Models
=======================================================

Downloads EXACT pre-trained models for:
1. Roof/Building Detection from Satellite Imagery
2. Roof Damage/Defect Detection

NO TRAINING REQUIRED - These are production-ready models!
"""

import os
import sys
import subprocess
from pathlib import Path
import shutil


def install_and_import(package, import_name=None):
    """Install package if needed and import it."""
    if import_name is None:
        import_name = package
    try:
        return __import__(import_name)
    except ImportError:
        print(f"[INSTALL] {package}...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", package, "-q"])
        return __import__(import_name)


def download_model(model_id, filename, save_path, models_dir):
    """Download a specific model file from Hugging Face."""
    from huggingface_hub import hf_hub_download
    
    print(f"\n{'='*60}")
    print(f"[DOWNLOADING] {model_id}")
    print(f"[FILE] {filename}")
    print(f"{'='*60}")
    
    try:
        downloaded_path = hf_hub_download(
            repo_id=model_id,
            filename=filename,
            local_dir=models_dir,
            local_dir_use_symlinks=False
        )
        
        # Copy to simple location
        final_path = models_dir / save_path
        final_path.parent.mkdir(parents=True, exist_ok=True)
        
        if Path(downloaded_path).exists():
            shutil.copy(downloaded_path, final_path)
            size_mb = final_path.stat().st_size / (1024 * 1024)
            print(f"[SUCCESS] Saved to: {final_path}")
            print(f"[SIZE] {size_mb:.1f} MB")
            return final_path
            
    except Exception as e:
        print(f"[ERROR] {e}")
        return None


def main():
    print("=" * 70)
    print("   AI ROOF DAMAGE DETECTION - MVP MODEL DOWNLOADER")
    print("   Ready-to-use pre-trained models - NO TRAINING NEEDED!")
    print("=" * 70)
    
    # Setup directories
    script_dir = Path(__file__).parent
    project_dir = script_dir.parent
    models_dir = project_dir / "models"
    models_dir.mkdir(exist_ok=True)
    
    # Install dependencies
    print("\n[SETUP] Installing dependencies...")
    install_and_import("huggingface_hub", "huggingface_hub")
    
    # Track downloaded models
    downloaded = {}
    
    # =========================================================================
    # MODEL 1: ROOF/BUILDING SEGMENTATION
    # Trained on satellite imagery for building detection
    # =========================================================================
    print("\n" + "=" * 70)
    print("MODEL 1: ROOF/BUILDING SEGMENTATION (Satellite Imagery)")
    print("Source: keremberke/yolov8m-building-segmentation")
    print("=" * 70)
    
    roof_model = download_model(
        model_id="keremberke/yolov8m-building-segmentation",
        filename="best.pt",
        save_path="roof_detector.pt",
        models_dir=models_dir
    )
    if roof_model:
        downloaded["roof_detector"] = roof_model
    
    # Also download smaller version as backup
    roof_model_small = download_model(
        model_id="keremberke/yolov8s-building-segmentation",
        filename="best.pt",
        save_path="roof_detector_small.pt",
        models_dir=models_dir
    )
    if roof_model_small:
        downloaded["roof_detector_small"] = roof_model_small
    
    # =========================================================================
    # MODEL 2: ROOF DAMAGE/DEFECT DETECTION
    # Trained YOLOv8 model for roof defect detection
    # =========================================================================
    print("\n" + "=" * 70)
    print("MODEL 2: ROOF DAMAGE/DEFECT DETECTION")
    print("Source: JGuevara-12/yolo-roof-damage")
    print("=" * 70)
    
    damage_model = download_model(
        model_id="JGuevara-12/yolo-roof-damage",
        filename="yolov8/weights/best.pt",
        save_path="damage_detector.pt",
        models_dir=models_dir
    )
    if damage_model:
        downloaded["damage_detector"] = damage_model
    
    # =========================================================================
    # CREATE CONFIGURATION FILE
    # =========================================================================
    print("\n" + "=" * 70)
    print("CREATING CONFIGURATION")
    print("=" * 70)
    
    env_content = """# AI Roof Damage Detection - Configuration
# ==========================================
# Generated by download_mvp_models.py

# Google Maps API Key (REQUIRED - Get from Google Cloud Console)
GOOGLE_MAPS_API_KEY=your_google_maps_api_key_here

# Model Paths (Pre-trained models - ready to use!)
# ------------------------------------------------
# Roof Detection (trained on satellite imagery for building segmentation)
ROOF_MODEL_PATH=./models/roof_detector.pt

# Damage Detection (trained on roof defects)
DAMAGE_MODEL_PATH=./models/damage_detector.pt

# Processing Settings
# -------------------
MAX_MEMORY_GB=4.0
BATCH_SIZE=4
CONFIDENCE_THRESHOLD=0.25
MAX_IMAGE_SIZE=1280

# API Settings
# ------------
RATE_LIMIT_QPS=10
DEBUG=false
HOST=0.0.0.0
PORT=8000
"""
    
    env_file = project_dir / ".env"
    with open(env_file, "w", encoding="utf-8") as f:
        f.write(env_content)
    print(f"[CREATED] {env_file}")
    
    # =========================================================================
    # SUMMARY
    # =========================================================================
    print("\n" + "=" * 70)
    print("DOWNLOAD SUMMARY")
    print("=" * 70)
    
    print("\nDownloaded Models:")
    for name, path in downloaded.items():
        if path and Path(path).exists():
            size_mb = Path(path).stat().st_size / (1024 * 1024)
            print(f"  [OK] {name}: {path} ({size_mb:.1f} MB)")
    
    print("\n" + "=" * 70)
    print("SETUP COMPLETE!")
    print("=" * 70)
    
    print("""
YOUR MVP IS READY!
==================

Models Downloaded:
  - roof_detector.pt     -> Detects roofs/buildings from satellite images
  - damage_detector.pt   -> Detects roof damage/defects

Next Steps:
-----------
1. Add your Google Maps API key to .env file:
   GOOGLE_MAPS_API_KEY=your_actual_key_here

2. Start the API:
   python -m api.main

3. Test at:
   http://localhost:8000/docs

Model Details:
--------------
- Roof Detection: YOLOv8m trained on satellite building imagery
- Damage Detection: YOLOv8 trained on roof defects

Both models use YOLOv8 architecture and work with the ultralytics library.
""")


if __name__ == "__main__":
    main()

